// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUsaeBLo_G-T8qxMp4ihvHEhxqaLUhlrM',
    appId: '1:402516551946:web:276b5a3a35b905779e32f3',
    messagingSenderId: '402516551946',
    projectId: 'test-86518',
    authDomain: 'test-86518.firebaseapp.com',
    databaseURL: 'https://test-86518-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-86518.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY8CBfqpcTRKp8rr4_Qk_UsS27V242xk8',
    appId: '1:402516551946:android:45467d422073bee89e32f3',
    messagingSenderId: '402516551946',
    projectId: 'test-86518',
    databaseURL: 'https://test-86518-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-86518.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7_g2J5hRNRrPJ0SohOWgOyNbLtguiiFc',
    appId: '1:402516551946:ios:6575f0430948e35f9e32f3',
    messagingSenderId: '402516551946',
    projectId: 'test-86518',
    databaseURL: 'https://test-86518-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-86518.appspot.com',
    iosClientId: '402516551946-k98r4m75i5q00qskb599gf2n8vcqrr4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.dektodo',
  );
}
